apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdxss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdxss
  template:
    metadata:
      labels:
        app: mdxss
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: mdxss
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "4ae78c57-73ef-4c71-b134-cf3f4b9a8f86"
        - name: Vless_Path
          value: "/kbhma"
        - name: Vmess_UUID
          value: "4ae78c57-73ef-4c71-b134-cf3f4b9a8f86"
        - name: Vmess_Path
          value: "/btejx"
        - name: Share_Path
          value: "/v2link"
